# fly.toml app configuration file generated for rsshub-superyi on 2023-09-15T13:53:52+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rsshub-superyi"
primary_region = "hkg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[[services]]
  protocol = "tcp"
  internal_port = 1200
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
